### ISSUE TITLE
Download notifications cover the screen with the exact same notification

### ISSUE THREAD

**Issue by TheRouce** [ollama-webui/ollama-webui#140] opened 2023-11-24 21:45 UTC
**Describe the bug**
Download notifications cover the screen with the exact same notification

**To Reproduce**
1. Go to models tab in the settings
2. Download any model

**Expected behavior**
A loading bar showing the progress of download

**Screenshots**
![image](https://github.com/ollama-webui/ollama-webui/assets/40551268/81f2cfed-78df-49b1-a43c-205ede1e5c23)

**Comment by tjbck** [comment] 2023-11-24 21:51
Hi, this issue has been addressed with the latest version, please try again and keep us updated, Thanks!

Duplicate of #128

**Closed** 2023-11-24 21:51 UTC

**Comment by TheRouce** [comment] 2023-11-25 01:47
Ah sorry I didn't check closed issues, it does work after building again
