### ISSUE TITLE
Import documents

### ISSUE THREAD

**Issue by pdavis68** [ollama-webui/ollama-webui#117] opened 2023-11-17 19:37 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A button that allows user to import documents into the conversation, similar to how ChatGPT, Perplexity or Claude do.

**Describe alternatives you've considered**
Turning the documents into text and pasting them, but that's painful.

**Additional context**
Nothing comes to mind.

**Comment by tjbck** [comment] 2023-11-17 19:45
Hi, Thanks for the suggestion. Let's continue our discussion on #31.

**Comment by tjbck** [comment] 2023-11-17 19:45
Duplicate of #31

**Closed by tjbck** 2023-11-17 19:45 UTC
