### ISSUE TITLE
Separate the Chat logic from the system logic

### ISSUE THREAD

**Issue by oliverbob** [ollama-webui/ollama-webui#210] opened 2023-12-13 15:24 UTC
Is there a way to create or separate the chat logic from the system/administrative logic? Its good to be able to add a feature that allows server owners to disable/enable features or settings or administrator privileges (at build or at runtime), such as:

- Chat Only
- Disable Model View (disable dropdown selection of models)
- Have a default model
- Hide download
- Enable default model
- Disable Settings View (or at least, show only parts of system settings). This is beneficial to protect accidental deletion of models.
- Enable search view (in stead of chat interface, bring the text area to the center of the screen (just like google search).

If contributors are busy, I'd like to be able to know the actual files that deals with this view, so I can play around with it.

Overall, I'm happy with the result of the latest release. Kudos to the contributors.

Thanks.

**Comment by tjbck** [comment] 2023-12-13 15:50
Hi, Thanks for the suggestion. RBAC is a feature that's being developed, stay tuned. Thanks. Duplicate of #68

**Closed by tjbck** 2023-12-13 15:50 UTC

**Comment by turnercore** [comment] 2023-12-24 18:20
> Hi, Thanks for the suggestion. RBAC is a feature that's being developed, stay tuned.
> 
> As for the all other numerous features you're requesting, I do not plan on adding them (non-core) in the near future, and will be only focusing on adding core features, so you would have to fork the repo and add features to the frontend and the backend yourself. Please refer to the code in the `/src/lib` and `/src/routes` for the frontend, `/backend` directory for the backend. Thanks. Duplicate of #68

Would you welcome PRs that add non-core features, or would you rather someone fork the project if they want to add non-core features?
