### ISSUE TITLE
Add support for SSL/HTTPS

### ISSUE THREAD

**Issue by TylerSelden** [ollama-webui/ollama-webui#429] opened 2024-01-08 15:09 UTC
**Is your feature request related to a problem? Please describe.**
I run this under my domain name, but this has no SSL support, rendering it unusable.

**Describe the solution you'd like**
It would be great to have SSL/HTTPS support added, where a domain's SSL certificate could be added.

**Describe alternatives you've considered**
I've considered proxying through a separate server, but that seems like more of a hassle then just using SSH, at least for the time being.

**Additional context**
N/A

**Comment by TylerSelden** [comment] 2024-01-08 15:36
Update: trying to make an nginx HTTP -> HTTPS proxy doesn't work; The web UI returns this error: "Ollama: 403 Client Error: Forbidden for url: http://localhost:11434/api/chat".

**Comment by justinh-rahb** [comment] 2024-01-08 16:23
I'm running it behind an HTTPS-HTTP reverse-proxy without issues, don't think the problem is in ollama-webui. Would suggest checking your nginx config with some other app to verify your SSL is working first.

**Comment by TylerSelden** [comment] 2024-01-08 16:38
It looks like the problem involved ollama API access control. For some reason, when I accessed the default HTTP:8080, it worked just fine, but I got `403: Forbidden` when using the Nginx HTTPS proxy. My solution was to add an environment variable that allowed API access from my website's domain name (OLLAMA_ORIGINS=https://mysite.com), and it works fine now.

I'm opting not to close this issue, though, as it would still be a good feature, and this is just a workaround.

**Comment by tjbck** [comment] 2024-01-09 03:10
Hi, Thanks for creating this feature request! I'll close this request as not planned as adding direct HTTPS support seems like it's outside the scope of this project. However, I'll take a look and see if there are any quick updates that could accommodate your case, but in the meantime, please use reverse proxy tools like nginx for optimal https support. Also, Feel free to add documentation for it by creating a PR, Thanks!

**Closed by tjbck** 2024-01-09 03:10 UTC
