### ISSUE TITLE
Account activation issue

### ISSUE THREAD

**Issue by developdeez** [ollama-webui/ollama-webui#608] opened 2024-01-31 03:43 UTC
Why do we need to acitvate an account for this???

Anyhew it causes issues and prevents login. Maybe remove it?

**Comment by justinh-rahb** [comment] 2024-01-31 04:07
This issue is a duplicate of closed issues #376 and #430.

If you're seeking a basic interface intended for a single user without login functionality, I recommend considering the Lite version, which can be found [here](https://github.com/ollama-webui/ollama-webui-lite).

Alternatively, if you desire additional features such as RAG and OpenAI API connection, creating a single account on the full version should suffice for you. It's important to note that authentication is local to your instance, there is no sharing of information with external parties. Currently, session timeouts are not implemented, so your account will remain logged in indefinitely until you logout.

**Closed** 2024-01-31 04:37 UTC
