### ISSUE TITLE
Formatting in for ```hcl and ```tf code response does not show code blocks properly.

### ISSUE THREAD

**Issue by mjtechguy** [ollama-webui/ollama-webui#610] opened 2024-01-31 15:17 UTC
# Bug Report

## Description

**Bug Summary:**
Seems the "```hcl" and "```tf" items are not respected the same as ```html items in the UI. When requesting Terraform code, it does not properly format the code block in the UI.

**Steps to Reproduce:**
1. Load "dolphin-mixtral" or "codellama" in Ollama
2. Request some terraform code with a prompt like "Can you provide complete terraform code with variable in terraform.tfvars for an AWS VPC, 1 private subnet, 1 public subnet".
3. Output is not properly show in the code block

**Expected Behavior:**
The expectation is that the code is shown as a proper code block in the UI

**Actual Behavior:**
The ```hcl and ```tf code flags are not properly shown like ```html is as a code block.

## Environment

- **Operating System:** Linux/Docker
- **Browser (if applicable):** : Chrome/Brave

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I have reviewed the troubleshooting.md document.

## Logs and Screenshots

**Browser Console Logs:**
NA

**Docker Container Logs:**
NA

**Screenshots (if applicable):**
![image](https://github.com/ollama-webui/ollama-webui/assets/29070994/38b19a48-3e05-4692-88eb-4ed4b270e479)

## Installation Method

Installed using Docker

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment] 2024-02-01 09:20
Unable to reproduce the issue :/

![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/57ddbd8c-37dc-4ec0-8f1f-5b1b49bde225)

![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/b904e739-8ad8-42db-8bea-14673a26e32b)


I'll close this issue for now as I highly suspect that there was an issue with the model-end, if not you might want to try updating to the latest version and see if that fixes your issue! Keep us updated!

**Closed by tjbck** 2024-02-01 09:20 UTC
