### ISSUE TITLE
Tolerate interrupted model downloads

### ISSUE THREAD

**Issue by robertvazan** [ollama-webui/ollama-webui#458] opened 2024-01-12 10:43 UTC
# Bug Report

## Description

**Bug Summary:**
If model download is interrupted (perhaps by restarting ollama as a workaround to #456), WebUI gets stuck on the download. It is impossible to retry the download nor is it possible to download anything else. The problem persists after WebUI restart.

**Steps to Reproduce:**
1. Start download of some model.
2. Restart ollama to interrupt the download.

**Expected Behavior:**
Download status is cleared and new download attempts are possible.

**Actual Behavior:**
UI is stuck in download state with progress bar and with download button disabled. This state persists after WebUI restart.

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I have reviewed the troubleshooting.md document.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

**Comment by robertvazan** [comment] 2024-01-12 21:08
Update: The stuck download disappears and new model downloads are possible after some time. This seems to be due to timeout rather than any user input.

**Comment by jokin** [comment] 2024-01-16 13:21
when you restar ollama the partial downloads are pruned, so maybe thats what happened.

**Comment by justinh-rahb** [comment] 2024-01-18 05:04
Lately, while working with larger models, I have encountered some disruptions due to my WAN failing over to backup. If the download progress doesn't vanish by itself eventually during these events, refreshing the page resolves it; however, upon re-downloading the model, the progress bar returns but has restarted progress automatically. Interestingly, should you close or refresh Ollama WebUI during this time, inputting the previously downloading model name will bring back the progress bar. It appears that in these instances, the background task can restart itself and persists as Ollama continues to download without needing a full reset. I have been unable to reproduce any permanently stuck downloads so far; at worst, refreshing and starting over has sufficed.

**Comment by robertvazan** [comment] 2024-01-18 09:20
I cannot reproduce this anymore. Has anything changed that could have an effect on the issue?

**Comment by tjbck** [comment] 2024-01-18 20:00
@robertvazan not that I know of 😅, I'll close this issue then!

**Closed by tjbck** 2024-01-18 20:00 UTC
