### ISSUE TITLE
feat : Add Hover Hints for Left Side Panel Items

### ISSUE THREAD

**Issue by hemangjoshi37a** [ollama-webui/ollama-webui#515] opened 2024-01-18 05:18 UTC
**Feature Description:**
The objective is to implement hover-over hints for each item located in the left side panel of the interface. These hints should provide a short description of the item's purpose or functionality. This feature is particularly aimed at improving user understanding and navigation for items like `Modelfies`, `Prompts`, and `Documents`.

**Functionality:**
- When a user hovers their mouse over any item in the left side panel, a small tooltip or hint should appear.
- This tooltip will contain a concise yet informative description of the item's function or purpose.

**Example:**
- Hovering over `Modelfies` might display a hint like "Configure and manage your model settings."
- Hovering over `Prompts` could show "Access and create new prompts."
- For `Documents`, the hint might be "View and organize your documents."

**Benefits:**
- Enhances user experience by providing immediate contextual information, aiding in navigation.
- Especially helpful for new users or those unfamiliar with the specific terminology or layout of the application.
- Can improve the overall usability and accessibility of the interface.

**Design Considerations:**
- The design of the hints should be non-intrusive and should not clutter the interface.
- Hints should be clearly legible, with a font size and color that are easy to read but not distracting.
- Care should be taken to ensure that the feature is responsive and functions well across different devices and screen sizes.

**Implementation:**
- The implementation should be consistent with the overall design language of the application.
- It should be ensured that the feature is lightweight and does not negatively impact the performance of the application.

This feature aims to make the application more intuitive and user-friendly, reducing the learning curve for new users and enhancing the efficiency of navigation for all users.

**Comment by tjbck** [comment] 2024-01-18 05:20
Duplicate of #259 #277

**Closed by tjbck** 2024-01-18 05:20 UTC
