### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by henrywithu** [ollama-webui/ollama-webui#146] opened 2023-11-25 19:10 UTC
Thanks for the awesome web ui.
It will be appreciated if there's a login page since I'm deploying it on public web

**Comment by tjbck** [comment] 2023-11-25 19:18
Hi, Thanks for the suggestion, we're working on this feature and should be added in the near future. Stay in tune, Thanks!

Duplicate of #68

**Closed by tjbck** 2023-11-25 19:18 UTC
