### ISSUE TITLE
Multimodal file attachment to talk to document.

### ISSUE THREAD

**Issue by oliverbob** [ollama-webui/ollama-webui#233] opened 2023-12-15 17:23 UTC
The latest ollama release allows LLM to read the content of attachments (not just images), being the easiest way to talk to a document on the go (thanks to the ollama team). 

But It is not yet currently being supported by recent commits, except when the attachment is an image. Ollama users would find it useful for this UI. I hope this can be included as an urgent task in your workload :smile: 

Your efforts are highly appreciated. 

:heartbeat:

Thanks.

**Comment by tjbck** [comment] 2023-12-15 17:30
Hi, RAG is one of the features thats being actively worked on, Stay tuned. 

Also, it would be greatly appreciated if people could check other issues/discussions in the project repo before creating a new one, as it takes away a lot of my time answering and closing them which could've been spent adding new features to the project, so please advise other people if you can. Thanks in advance! Duplicate of #31

**Closed by tjbck** 2023-12-15 17:31 UTC
