### ISSUE TITLE
Add Support for Text File Upload

### ISSUE THREAD

**Issue by TanvirOnGH** [ollama-webui/ollama-webui#60] opened 2023-11-05 09:39 UTC
**Is your feature request related to a problem? Please describe.**
Currently, the project lacks the capability to handle text file uploads, such as markdown and PDF files, for the purpose of summarization and Q&A. This limitation restricts users from efficiently extracting information from documents.

**Describe the solution you'd like**
I propose the addition of a feature that allows users to upload text files in formats like markdown, PDF. ollama-webui should be able to process these files to provide summaries and answer user queries based on the content within the uploaded documents. This enhancement would significantly improve the versatility and usefulness of the ollama-webui.

**Describe alternatives you've considered**
An alternative to supporting file uploads could be manual copying and pasting of text content into the chat interface, but this approach is time-consuming and error-prone. Another alternative is integrating with external document management systems, but this might be less user-friendly and may introduce privacy concerns.

**Additional context**
In many use cases, users need to extract specific information or summaries from existing documents in their possession. Adding support for text file uploads, especially in common formats like markdown and PDF, would greatly enhance the capabilities and make it a valuable tool for content processing and information retrieval. This feature aligns with the growing demand for efficient document processing and information extraction tools in various domains.

**Comment by TanvirOnGH** [comment] 2023-11-05 17:58
Possibly support all the types of file formats same as gpt4all localdocs as mentioned [here](https://docs.gpt4all.io/gpt4all_chat.html#how-localdocs-works):
```txt
["txt", "doc", "docx", "pdf", "rtf", "odt", "html", "htm", "xls", "xlsx", "csv", "ods", "ppt", "pptx", 
"odp", "xml", "json", "log", "md", "org", "tex", "asc", "wks",
"wpd", "wps", "wri", "xhtml", "xht", "xslt", "yaml", "yml", "dtd", "sgml", "tsv", "strings", "resx",
"plist", "properties", "ini", "config", "bat", "sh", "ps1", "cmd", "awk", "sed", "vbs", "ics", "mht",
"mhtml", "epub", "djvu", "azw", "azw3", "mobi", "fb2", "prc", "lit", "lrf", "tcr", "pdb", "oxps",
"xps", "pages", "numbers", "key", "keynote", "abw", "zabw", "123", "wk1", "wk3", "wk4", "wk5", "wq1",
"wq2", "xlw", "xlr", "dif", "slk", "sylk", "wb1", "wb2", "wb3", "qpw", "wdb", "wks", "wku", "wr1",
"wrk", "xlk", "xlt", "xltm", "xltx", "xlsm", "xla", "xlam", "xll", "xld", "xlv", "xlw", "xlc", "xlm",
"xlt", "xln"]
```

**Comment by tjbck** [comment] 2023-11-05 18:04
Hi, Thanks for the suggestion. Document parser (or RAG) functionality was something I've been planning on implementing for a while now. I'm just not sure what would be the best way to approach this as I'd like to keep this web ui project as lightweight as possible. One possible way to implement this feature could be making it purely client-side but I don't see that being a viable solution as there are people who use the web ui via their phone browser and the experience would not be great. Do you have any technical implementation ideas in mind? I'm quite overwhelmed at the moment so if you manage to implement the feature, PR is always welcome. Thanks!

**Comment by tjbck** [comment] 2023-11-05 18:09
duplicate of #31

**Closed** 2023-11-05 18:09 UTC
