### ISSUE TITLE
Support for Azure OpenAI endpoints

### ISSUE THREAD

**Issue by bharath063** [ollama-webui/ollama-webui#258] opened 2023-12-22 06:47 UTC
**Is your feature request related to a problem? Please describe.**
I have an Azure OpenAI API deployment. This has a custom deployment(let's say mycompany.azure.com). How do I configure this domain and use my token instead of the default openAI endpoint?

**Describe the solution you'd like**
Provide a section in the UI to configure custom endpoints for OpenAI. The token field can remain the same

**Comment by tjbck** [comment] 2023-12-22 06:56
Hi! configurable OpenAI endpoint feature's being actively discussed at #230, Let's continue our discussion there! Duplicate of #230

**Closed by tjbck** 2023-12-22 06:56 UTC
