### ISSUE TITLE
Uh-oh! There was an issue connecting to Ollama.

### ISSUE THREAD

**Issue by ralyodio** [ollama-webui/ollama-webui#241] opened 2023-12-18 18:17 UTC
Uh-oh! There was an issue connecting to Ollama.

**Comment by ralyodio** [comment] 2023-12-18 19:56
is this on my side? or is ollama.ai servers down?

**Comment by tjbck** [comment] 2023-12-18 20:09
Hi, We cannot help you with the limited information you've included, please provide the commands you used to install, browser console logs and docker container logs. Thanks.

**Comment by justinh-rahb** [comment] 2023-12-18 20:53
> is this on my side? or is ollama.ai servers down?

@ralyodio The Ollama WebUI does not interact with ollama.ai servers, but rather only communicates with a locally running instance of Ollama on the same machine or another machine via API. Therefore, if there is an issue, it would be specific to your local installation and not related to any third-party servers on the internet.

**Comment by ralyodio** [comment] 2023-12-19 00:41
i can't sseem to get it to work w/o using docker and even with docker it worked the first time I ran build, but after that I always get server connection fail

**Comment by ralyodio** [comment] 2023-12-19 00:47
`[2023-12-19T00:46:09.652Z]  "GET /ollama/api/tags" Error (404): "connect ECONNREFUSED ::1:5432"`

this is what i get in the logs.

**Comment by ralyodio** [comment] 2023-12-19 01:01
Here's what I'm doing:

`OLLAMA_HOST=0.0.0.0 OLLAMA_ORIGINS=* ollama serve`

in another shell I run:

`OLLAMA_API_BASE_URL=http://localhost:11434 PORT=5432 npm start`

and when I go to https://ai.profullstack.com the UI loads but can't connect to ollama server. In the ollama server log I see a 404 for `/api/v1/` but that's it.

Here's my nginx config incase:

```
    location /api {
#        auth_basic "ai access required";
#        auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_pass http://localhost:11434/api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_cache_bypass $http_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $remote_addr;
    }

    location / {
#        auth_basic "ai access required";
#        auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_pass http://localhost:5432;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_cache_bypass $http_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
```

**Comment by tjbck** [comment] 2023-12-19 01:23
Please refer to https://github.com/ollama-webui/ollama-webui#how-to-install-without-docker. Thanks

**Comment by ralyodio** [comment] 2023-12-19 01:33
Yeah I went through all that.

**Comment by tjbck** [comment] 2023-12-19 02:11
Hmm, I have no idea how exactly you have Ollama/Ollama WebUI set up, and If you follow all the steps outlined in the readme.md, you should have the webui up and running. 

Also, I cannot reproduce at all with the given information, Could you tell us more about your setup, as detailed as possible so that we can better help you with your issue? Thanks.

**Comment by oliverbob** [comment] 2023-12-19 02:46
> Yeah I went through all that.

Pull the latest ollama-webui and try the build method:

Remove/kill both ollama and ollama-webui in docker:
If ollama is not running on docker (sudo systemctl stop ollama)

If ollama is running on docker:
docker remove ollama ollama-webui.

docker compose up -d --build

[
Optional:
Then on the same terminal, try to do: ollama pull orca-mini:3b
]

Then open ollama-webui at [http://localhost:8080](http://localhost:8080/)

**Comment by ralyodio** [comment] 2023-12-19 02:50
As I've stated I'm not using docker.

**Comment by tjbck** [comment] 2023-12-19 03:08
We do not support the command`npm start` for deployment and is strictly for development purposes. Do you also have the backend running as outlined in the readme.md?

**Comment by ralyodio** [comment] 2023-12-19 03:47
yes

**Comment by ralyodio** [comment] 2023-12-19 04:04
I figured it out. I think its a bug with using `npm start`

I had to change the settings in the UI to use `/api` instead of `/ollama/api` and it connected!

**Comment by tjbck** [comment] 2023-12-19 04:31
Seems like you have not read the instructions here: https://github.com/ollama-webui/ollama-webui#how-to-install-without-docker, and you're using an unsupported method of installation, I'll close this issue.

If you'd like to follow the instructions provided, refer to the screenshot of the readme.md I took below, Thanks.
![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/a8e19067-5202-486f-abae-e01dd44c24c4)

**Comment by ralyodio** [comment] 2023-12-19 04:32
your instructions suck ass and you got a bug anyway, but hey what do i know. i've only been doing this 25 years.

**Closed by tjbck** 2023-12-19 04:31 UTC

**Comment by tjbck** [comment] 2023-12-19 04:35
Again, to reiterate `npm start` is not a supported method of deploying the webui, and it won't work unless you configure everything the right way. Thank you.

**Comment by oliverbob** [comment] 2023-12-20 03:47
TJ

> Again, to reiterate `npm start` is not a supported method of deploying the webui, and it won't work unless you configure everything the right way. Thank you.

Please only remove only the abusive part of comments, not the entire comments. I've been reading the convo in my email. Lets be open to developer frustrations. It happens at times.

Anyways, you have a very great work TJBCK. You're perhaps even better than Sam Altman. Cheers my friend. :+1: 

Thanks a lot.
