### ISSUE TITLE
Response Cut-off Issue in GPT-4 Vision Preview

### ISSUE THREAD

**Issue by CreatorGhost** [ollama-webui/ollama-webui#516] opened 2024-01-18 07:25 UTC
# Bug Report

## Description

**Bug Summary:**
Responses from the GPT-4 Vision Preview feature are being cut off after the first line, preventing users from receiving complete answers to their prompts.

**Steps to Reproduce:**
1. Go to the GPT-4 Vision Preview feature within the Ollama project.
2. Input a prompt that is expected to generate a multi-line response.
3. Observe that the generated response is incomplete, with only the first line being displayed before it gets cut off.

**Expected Behavior:**
The GPT-4 Vision Preview should generate and display the full response to the prompt, providing a complete and coherent answer.

**Actual Behavior:**
The response is truncated after the first line, leaving the user with an incomplete answer and hindering the functionality of the GPT-4 Vision Preview feature.

## Environment

- **Operating System:** macOS Big Sur
- **Browser (if applicable):** Chrome

**Comment by tjbck** [comment] 2024-01-19 04:19
Hi, Thanks for creating this issue! I've just checked the `GPT-4 Vision Preview` api myself, and it seems like the issue is from openAI prematurely sending a `data: [DONE]` response, not the webui.


<img width="555" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/25473318/4e89e309-401e-4f0f-9c88-d936c5effde0">


I'll be closing this issue as it seems like there isn't anything we can do from the webui, but if you manage to find a fix, feel free to make a PR!

**Closed by tjbck** 2024-01-19 04:19 UTC

**Comment by CreatorGhost** [comment] 2024-01-19 23:10
I have fixed the issue and raised the PR kindly check and merge.
https://github.com/ollama-webui/ollama-webui/pull/537
<img width="1431" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/46842909/52db73ef-3693-4447-9c42-b60bf523e0c7">
