### ISSUE TITLE
bug: Modelfiles are not loaded on the chat page

### ISSUE THREAD

**Issue by keriati** [ollama-webui/ollama-webui#658] opened 2024-02-06 08:11 UTC
# Bug Report
It seems the modelfiles are not loaded on the chat page.
## Description
It seems the modelfiles are not loaded on the chat page.
**Bug Summary:**
It seems the modelfiles are not loaded on the chat page.

**Steps to Reproduce:**
- Go to ollama hub
- Add based dolphin mixtral
- Adjust the content so it starts with: 

```
FROM dolphin-mixtral:8x7b-v2.7-q5_K_M
```

- Save it
- on the modelfiles page click on Based Dolphin Mixtral
- get reidrected to chat page

**Expected Behavior:**
- chat page applies the modelfile settings

**Actual Behavior:**
- chat page does not apply the modelfile settings

## Environment

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
macos

- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]
latest chrome
latest firefox

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I have reviewed the troubleshooting.md document.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
```
Array []
initNewChat 
<empty string>.    <<< here should be the modelfile logged out I think
Object { status: true, version: "v1.0.0-alpha.92", auth: true, default_models: null, default_prompt_suggestions: (4) […] }
```
**Docker Container Logs:**
N/A

**Screenshots (if applicable):**
N/A

## Installation Method
Installed with docker based on readme

## Additional Information
N/A

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment] 2024-02-06 08:13
Unable to reproduce the issue, could you verify that you're on the latest version of the webui?

![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/0775e5fb-4bce-4cad-8d84-457502c462b0)

**Comment by keriati** [comment] 2024-02-06 08:15
Sure:

![Screenshot 2024-02-06 at 09 14 53](https://github.com/ollama-webui/ollama-webui/assets/439392/76fbd5fe-462a-4bbd-923b-81d93b9bb4a5)

Can it be the problem that the FROM part is adjusted?

**Comment by tjbck** [comment] 2024-02-06 08:16
![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/20598f62-dbcd-4532-985e-9d54857395aa)
![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/356840a2-cfdb-4ca9-83f8-fbd79a8d4e3e)

You're saying can't get to the second part of the screenshot correct?

**Comment by keriati** [comment] 2024-02-06 08:18
Modelfiles page:
![Screenshot 2024-02-06 at 09 16 45](https://github.com/ollama-webui/ollama-webui/assets/439392/d948dc90-1bea-4202-b220-c5f9bd113e1d)

Click on Based Dolphin result:
![Screenshot 2024-02-06 at 09 17 12](https://github.com/ollama-webui/ollama-webui/assets/439392/9844b05d-d29e-4d8c-be27-e14d706c0f97)

**Comment by keriati** [comment] 2024-02-06 08:19
Model selection:

![Screenshot 2024-02-06 at 09 19 04](https://github.com/ollama-webui/ollama-webui/assets/439392/fb72d6b7-b258-4c38-bf63-5da3a4141287)

**Comment by keriati** [comment] 2024-02-06 08:24
thanks for the hint, I think I see now what is going on:
This is added to the URL when I click on the modefile page and it does not work:

```models=based-dolphin-mixtral%3Alatest```

this however works:

```?models=dolphin-mixtral:8x7b-v2.7-q5_K_M```

**Comment by tjbck** [comment] 2024-02-06 08:26
Did you also change the model tag name somehow? Could you provide use with the step by step guide with images on how we can reproduce the issue?

**Comment by keriati** [comment] 2024-02-06 08:27
So I only adjusted the FROM part of the model as I needed the bigger version:

![Screenshot 2024-02-06 at 09 26 53](https://github.com/ollama-webui/ollama-webui/assets/439392/332ee200-774a-4651-95bc-ab9bab31c66a)

**Comment by tjbck** [comment] 2024-02-06 08:29
And if you save and update, does that just take you back to the modelfiles page?

**Comment by keriati** [comment] 2024-02-06 08:32
okay, so I pressed save and update now again and now it works 

![Screenshot 2024-02-06 at 09 31 55](https://github.com/ollama-webui/ollama-webui/assets/439392/8bbaf721-28ee-407d-be1e-20254ad0d7fd)

**Comment by keriati** [comment] 2024-02-06 08:33
Also now in the model selection i get this based-dolphin-mixtral:latest instead of dolphin-mixtral:8x7b-v2.7-q5_K_M

**Comment by tjbck** [comment] 2024-02-06 08:34
Strange, that should've been the case in the first place. Maybe there was a connection issue with your Ollama instance. I'll close this for now but feel free to ping me if you encounter the same issue again, Thanks!

**Closed by tjbck** 2024-02-06 08:34 UTC
