### ISSUE TITLE
Standalone ollama-webui

### ISSUE THREAD

**Issue by Herz3h** [ollama-webui/ollama-webui#154] opened 2023-11-27 14:32 UTC
**Describe the bug**
I just pulled this webui with the following docker command:

`docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway --name ollama-webui --restart always ghcr.io/ollama-webui/ollama-webui:main`

I already had ollama running separately.

And the default Ollama Server URL was `/ollama/api`

Don't know if this has been changed lately on ollama, but the correct endpoint seems to be `/api`

**To Reproduce**
Install ollama separately, then run òllama serve`
Then run following docker-command: `docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway --name ollama-webui --restart always ghcr.io/ollama-webui/ollama-webui:main`

It should say connection server failed because the endpoint is /api

**Expected behavior**
Should maybe mention this in the part of the readme talking about the standalone ollama-webui version

**Screenshots**
NA

**Desktop (please complete the following information):**
- Debian 11
- Chrome 119.0.6045.159

**Additional context**

**Comment by tjbck** [comment] 2023-11-28 05:42
Hi, Could you verify that both Ollama WebUI and the Ollama instance is running on the same machine? I'll close this for now as `/ollama/api` route is the backend reverse proxy route which redirects to your Ollama api `/api` route and is how it's supposed to be by design. Keep us updated, Thanks.

**Closed by tjbck** 2023-11-28 05:42 UTC
